version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket aws-sam-cicddemo-bucket --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml