version: 0.2
phases:
  install:
    commands:
      - aws s3 mb s3://bchin-lambda-pipeline --region us-east-1
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket bchin-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml